-------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------ GRUPO ANONYMOUS --------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

USE [GD1C2021]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET NOCOUNT OFF
GO

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------ DROP -------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
/****** Vista V_COMPRAS_PC ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_COMPRAS_PC' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_COMPRAS_PC];
GO

/****** Vista V_VENTAS_PC ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_VENTAS_PC' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_VENTAS_PC];
GO

/****** Vista V_PROMEDIO_STOCK_PC ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_PROMEDIO_STOCK_PC' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_PROMEDIO_STOCK_PC];
GO

/****** Vista V_PRECIO_PC_VENTA ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_PRECIO_PC_VENTA' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_PRECIO_PC_VENTA];
GO

/****** Vista V_PRECIO_PC_COMPRA ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_PRECIO_PC_COMPRA' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_PRECIO_PC_COMPRA];
GO

/****** Vista V_CANT_PC_COMPRA ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_CANT_PC_COMPRA' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_CANT_PC_COMPRA];
GO

/****** Vista V_CANT_PC_VENTA ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_CANT_PC_VENTA' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_CANT_PC_VENTA];
GO

/****** Vista V_GANANCIAS_PC ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_GANANCIAS_PC' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_GANANCIAS_PC];
GO

/****** Vista V_PRECIO_ACC_COMPRA ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_PRECIO_ACC_COMPRA' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_PRECIO_ACC_COMPRA];
GO

/****** Vista V_PRECIO_ACC_VENTA ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_PRECIO_ACC_VENTA' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_PRECIO_ACC_VENTA];
GO

/****** Vista V_GANANCIAS_ACC ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_GANANCIAS_ACC' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_GANANCIAS_ACC];
GO

/****** Vista V_PROMEDIO_STOCK_ACC ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_PROMEDIO_STOCK_ACC' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_PROMEDIO_STOCK_ACC];
GO

/****** Vista V_MAX_STOCK_ACC ******/
IF EXISTS(SELECT 1 FROM SYS.VIEWS WHERE NAME='V_MAX_STOCK_ACC' AND TYPE='V')
DROP VIEW [ANONIMOUS].[V_MAX_STOCK_ACC];
GO

/****** Tabla BI_STOCK_ACC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_STOCK_ACC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_STOCK_ACC]
GO

/****** Tabla BI_COMPRA_PC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_COMPRA_PC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_COMPRA_PC]
GO

/****** Tabla BI_COMPRA_ACC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_COMPRA_ACC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_COMPRA_ACC]
GO

/****** Tabla BI_VENTA_PC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_VENTA_PC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_VENTA_PC]
GO

/****** Tabla BI_VENTA_ACC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_VENTA_ACC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_VENTA_ACC]
GO

/****** Tabla BI_TIEMPO ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_TIEMPO]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_TIEMPO]
GO

/****** Tabla BI_SUCURSAL ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_SUCURSAL]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_SUCURSAL]
GO

/****** Tabla BI_CIUDAD ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_CIUDAD]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_CIUDAD]
GO

/****** Tabla BI_PC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_PC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_PC]
GO

/****** Tabla BI_ACCESORIO ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_ACCESORIO]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_ACCESORIO]
GO

/****** Tabla BI_RANGO_EDAD ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_RANGO_EDAD]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_RANGO_EDAD]
GO

/****** Tabla BI_DISCO_RG ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_DISCO_RG]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_DISCO_RG]
GO

/****** Tabla BI_MEM_RAM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_MEM_RAM]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_MEM_RAM]
GO

/****** Tabla BI_MICRO_PRO ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_MICRO_PRO]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_MICRO_PRO]
GO

/****** Tabla BI_PLA_VIDEO ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[BI_PLA_VIDEO]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[BI_PLA_VIDEO]
GO

/****** Tabla COMPRAS_ACC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[COMPRAS_ACC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[COMPRAS_ACC]
GO

/****** Tabla VENTAS_ACC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[VENTAS_ACC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[VENTAS_ACC]
GO

/****** Tabla COMPRAS_PC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[COMPRAS_PC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[COMPRAS_PC]
GO

/****** Tabla VENTAS_PC ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ANONIMOUS].[VENTAS_PC]') AND type in (N'U'))
	DROP TABLE [ANONIMOUS].[VENTAS_PC]
GO
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------ CREATE TABLES  ---------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

/****** Tabla BI_TIEMPO ******/
CREATE TABLE [ANONIMOUS].[BI_TIEMPO] (
	[TIEMPO_ID]   [decimal](6, 0) NOT NULL,
	[TIEMPO_ANIO] [decimal](4, 0) NOT NULL,
    [TIMEPO_MES]  [decimal](2, 0) NOT NULL,
	CONSTRAINT [PK_BI_Tiempo] PRIMARY KEY ([TIEMPO_ID] ASC)
);
GO

/****** Tabla BI_CIUDAD ******/
CREATE TABLE [ANONIMOUS].[BI_CIUDAD] (
	[CIUDAD_ID]  [decimal](18, 0) NOT NULL,
	[CIUDAD_NOM] [nvarchar](255)  NOT NULL,
	CONSTRAINT [PK_BI_Ciudad] PRIMARY KEY ([CIUDAD_ID] ASC)
);
GO
/****** Tabla BI_SUCURSAL ******/
CREATE TABLE [ANONIMOUS].[BI_SUCURSAL] (
	[SUCURSAL_ID]     [decimal](18, 0) NOT NULL,
	[SUCURSAL_MAIL]   [nvarchar](255)  NOT NULL,
	[SUCURSAL_TEL]    [decimal](18, 0) NOT NULL,
	[SUCURSAL_DIR]    [nvarchar](255)  NOT NULL,
	[SUCURSAL_CIUDAD] [decimal](18, 0) NOT NULL,
	CONSTRAINT [PK_BI_Sucursal] PRIMARY KEY ([SUCURSAL_ID] ASC)
);
GO

/****** Tabla BI_RANGO_EDAD ******/
CREATE TABLE [ANONIMOUS].[BI_RANGO_EDAD] ( 
	[RANGO_EDAD_ID]      [decimal] (18, 0) NOT NULL,
	[RANGO_EDAD_DESC]	 [char] (30) NOT NULL, 
	CONSTRAINT [PK_BI_RANGO_EDAD] PRIMARY KEY ([RANGO_EDAD_ID] ASC)
);
GO

/****** Tabla BI_PC ******/
CREATE TABLE [ANONIMOUS].[BI_PC] ( 
	[PC_ID]	 [decimal] (18, 0) NOT NULL,
	[PC_COD] [nvarchar] (255)  NOT NULL,
	CONSTRAINT [PK_BI_PC] PRIMARY KEY ([PC_ID] ASC)
);

/****** Tabla BI_ACCESORIO ******/
CREATE TABLE [ANONIMOUS].[BI_ACCESORIO] ( 
	[ACCESORIO_ID]	  [decimal] (18, 0) NOT NULL,
	[ACCESORIO_COD]	  [nvarchar] (255)  NOT NULL,
	[ACCESORIO_DESC]  [nvarchar] (255)  NOT NULL,
	CONSTRAINT [PK_BI_Accesorio] PRIMARY KEY ([ACCESORIO_ID] ASC)
);

/****** Tabla BI_DISCO_RG ******/
CREATE TABLE [ANONIMOUS].[BI_DISCO_RG] (
	[DISCO_RG_ID]          [decimal](18, 0) NOT NULL, 
	[DISCO_RG_COD]		   [nvarchar](255),
	[DISCO_RG_TIPO]		   [nvarchar](255),
	[DISCO_RG_CAPACIDAD]   [nvarchar](255),
	[DISCO_RG_VELOCIDAD]   [nvarchar](255),
	[DISCO_RG_FABRICANTE]  [nvarchar](255),
	CONSTRAINT [PK_BI_Disco_Rigido] PRIMARY KEY ([DISCO_RG_ID] ASC)
);
GO

/****** Tabla BI_MEM_RAM ******/
CREATE TABLE [ANONIMOUS].[BI_MEM_RAM] (
	[MEM_RAM_ID]          [decimal](18, 0) NOT NULL, 
	[MEM_RAM_COD]		  [nvarchar](255),
	[MEM_RAM_TIPO]		  [nvarchar](255),
	[MEM_RAM_CAPACIDAD]   [nvarchar](255),
	[MEM_RAM_VELOCIDAD]   [nvarchar](255),
	[MEM_RAM_FABRICANTE]  [nvarchar](255),
	CONSTRAINT [PK_BI_Memoria_ram] PRIMARY KEY ([MEM_RAM_ID] ASC)
);
GO

/****** Tabla BI_MICRO_PRO ******/
CREATE TABLE [ANONIMOUS].[BI_MICRO_PRO] (
	[MICRO_PRO_ID]          [decimal](18, 0) NOT NULL, 
	[MICRO_PRO_COD]         [nvarchar](255),
	[MIC_PRO_VELOCIDAD]     [nvarchar](255),
	[MIC_PRO_FABRICANTE]    [nvarchar](255),
	[MIC_PRO_CANT_HILOS]	[decimal](18, 0),
	[MIC_PRO_CACHE]			[nvarchar](50),
	CONSTRAINT [PK_BI_Micro_Pro] PRIMARY KEY ([MICRO_PRO_ID] ASC)
);
GO

/****** Tabla BI_PLA_VIDEO ******/
CREATE TABLE [ANONIMOUS].[BI_PLA_VIDEO] (
	[PLA_VIDEO_ID]				 [decimal](18, 0) NOT NULL,
	[PLA_VIDEO_MODELO]			 [nvarchar](50),
	[PLA_VIDEO_CAPACIDAD]        [nvarchar](255),
	[PLA_VIDEO_VELOCIDAD]        [nvarchar](255),
	[PLA_VIDEO_FABRICANTE]       [nvarchar](255),
	[PLA_VIDEO_VIDEO_CHIPSET]    [nvarchar](50),
	CONSTRAINT [PK_BI_Placa_video] PRIMARY KEY ([PLA_VIDEO_ID] ASC)
);
GO

/****** Tabla COMPRAS_PC ******/
CREATE TABLE [ANONIMOUS].[COMPRAS_PC] (
	[COMPRAS_PC_ID]           [decimal](18, 0) IDENTITY,
	[COMPRAS_PC_NUM]          [decimal](18, 0), 
	[COMPRAS_PC_ID_PC]        [decimal](18, 0),
	[COMPRAS_PC_INDEX]        [decimal](18, 0),
	[COMPRAS_PC_ID_TIEMPO]    [decimal](6, 0),
	[COMPRAS_PC_ID_SUC]       [decimal](18, 0),
	[COMPRAS_PC_ID_DISCO_RG]  [decimal](18, 0),
	[COMPRAS_PC_ID_MEM_RAM]   [decimal](18, 0),
	[COMPRAS_PC_ID_MICRO_PRO] [decimal](18, 0),
	[COMPRAS_PC_ID_PLACA_V]   [decimal](18, 0),
	[COMPRAS_PC_FECHA]        [date],
	[COMPRAS_PC_PRECIO]       [decimal](18, 2),
	[COMPRAS_PC_CANT]         [decimal](18, 0),
    CONSTRAINT [PK_BI_COMPRAS_PC] PRIMARY KEY ([COMPRAS_PC_ID])
);
GO

/****** Tabla BI_COMPRA_PC ******/
CREATE TABLE [ANONIMOUS].[BI_COMPRA_PC] (
	[COMPRA_PC_ID]           [decimal](18, 0) IDENTITY, 
	[COMPRA_PC_ID_PC]        [decimal](18, 0),
	[COMPRA_PC_ID_SUC]       [decimal](18, 0),
	[COMPRA_PC_ID_TIEMPO]    [decimal](6, 0),
	[COMPRA_PC_ID_DISCO_RG]  [decimal](18, 0),
	[COMPRA_PC_ID_MEM_RAM]   [decimal](18, 0),
	[COMPRA_PC_ID_MICRO_PRO] [decimal](18, 0),
	[COMPRA_PC_ID_PLACA_V]   [decimal](18, 0),
	[COMPRA_PC_PRECIO_PROM]  [decimal](18, 2),
	[COMPRA_PC_CANT]         [decimal](18, 0),
    CONSTRAINT [PK_BI_COMPRA_PC] PRIMARY KEY ([COMPRA_PC_ID])
);
GO

/****** Tabla BI_COMPRA_ACC ******/
CREATE TABLE [ANONIMOUS].[BI_COMPRA_ACC] (
	[COMPRA_ACC_ID]           [decimal](18, 0) IDENTITY,
	[COMPRA_ACC_ID_ACC]	      [decimal](18, 0),
	[COMPRA_ACC_ID_SUC]       [decimal](18, 0),
	[COMPRA_ACC_ID_TIEMPO]    [decimal](6, 0),
	[COMPRA_ACC_PRECIO_PROM]  [decimal](18, 2),
	[COMPRA_ACC_CANT]         [decimal](18, 0),
    CONSTRAINT [PK_BI_COMPRA_ACC] PRIMARY KEY ([COMPRA_ACC_ID])
);
GO

/****** Tabla VENTAS_PC ******/
CREATE TABLE [ANONIMOUS].[VENTAS_PC] (
	[VENTAS_PC_ID]			 [decimal](18, 0) IDENTITY,
	[VENTAS_PC_NUM]		     [decimal](18, 0), 
	[VENTAS_PC_ID_PC]		 [decimal](18, 0),
	[VENTAS_PC_INDEX]		 [decimal](18, 0),
	[VENTAS_PC_ID_TIEMPO]	 [decimal](6, 0),
	[VENTAS_PC_ID_SUC]		 [decimal](18, 0),
	[VENTAS_PC_EDAD_CLI]     [decimal](18, 0),
	[VENTAS_PC_ID_DISCO_RG]  [decimal](18, 0),
	[VENTAS_PC_ID_MEM_RAM]   [decimal](18, 0),
	[VENTAS_PC_ID_MICRO_PRO] [decimal](18, 0),
	[VENTAS_PC_ID_PLACA_V]   [decimal](18, 0),	
	[VENTAS_PC_FECHA]        [date],
	[VENTAS_PC_PRECIO]       [decimal](18, 2),
	[VENTAS_PC_CANT]         [decimal](18, 0),
    CONSTRAINT [PK_VENTAS_PC] PRIMARY KEY ([VENTAS_PC_ID])
);
GO

/****** Tabla BI_VENTA_PC ******/
CREATE TABLE [ANONIMOUS].[BI_VENTA_PC] (
	[VENTA_PC_ID]			     [decimal](18, 0) IDENTITY,
	[VENTA_PC_ID_PC]		     [decimal](18, 0),
	[VENTA_PC_ID_SUC]		     [decimal](18, 0),
	[VENTA_PC_ID_TIEMPO]	     [decimal](6, 0),
	[VENTA_PC_ID_EDAD_CLI]       [decimal](18, 0),
	[VENTA_PC_ID_DISCO_RG]       [decimal](18, 0),
	[VENTA_PC_ID_MEM_RAM]        [decimal](18, 0),
	[VENTA_PC_ID_MICRO_PRO]      [decimal](18, 0),
	[VENTA_PC_ID_PLACA_V]        [decimal](18, 0),	
	[VENTA_PC_PRECIO_PROM]       [decimal](18, 2),
	[VENTA_PC_CANT]              [decimal](18, 0),
	[VENTA_PC_DIAS_STOCK_PROM]   [decimal](18, 0),
	[VENTA_PC_GANANCIA]          [decimal](18, 2),
    CONSTRAINT [PK_BI_VENTA_PC] PRIMARY KEY ([VENTA_PC_ID])
);
GO

/****** Tabla BI_VENTA_ACC ******/
CREATE TABLE [ANONIMOUS].[BI_VENTA_ACC] (
	[VENTA_ACC_ID]			      [decimal](18, 0) IDENTITY,
	[VENTA_ACC_ID_ACC]		      [decimal](18, 0),
	[VENTA_ACC_ID_SUC]		      [decimal](18, 0),
	[VENTA_ACC_ID_TIEMPO]	      [decimal](6, 0),	
	[VENTA_ACC_ID_EDAD_CLI]       [decimal](18, 0),
	[VENTA_ACC_PRECIO_PROM]       [decimal](18, 2),
	[VENTA_ACC_CANT]              [decimal](18, 0),
	[VENTA_ACC_DIAS_STOCK_PROM]   [decimal](18, 0),
	[VENTA_ACC_GANANCIA]          [decimal](18, 2),
    CONSTRAINT [PK_BI_VENTAS_ACC] PRIMARY KEY (VENTA_ACC_ID)
);
GO

/****** Tabla BI_STOCK_ACC ******/
CREATE TABLE [ANONIMOUS].[BI_STOCK_ACC] ( 
	[STOCK_ID]				[decimal] (18, 0) NOT NULL IDENTITY,
	[STOCK_SUCURSAL]		[decimal] (18, 0) NOT NULL,
	[STOCK_TIEMPO]			[decimal] (6, 0)  NOT NULL,
	[STOCK_CANTIDAD]		[decimal] (18, 0) NOT NULL,
	CONSTRAINT [PK_BI_STOCK_ACC] PRIMARY KEY ([STOCK_ID] ASC)
);
GO

/****** Tabla COMPRAS_ACC ******/
CREATE TABLE [ANONIMOUS].[COMPRAS_ACC] (
	[COMPRAS_ACC_ID]           [decimal](18, 0) IDENTITY,
	[COMPRAS_ACC_NUM]          [decimal](18, 0), 
	[COMPRAS_ACC_ID_ACC]       [decimal](18, 0),
	[COMPRAS_ACC_INDEX]        [decimal](18, 0),
	[COMPRAS_ACC_ID_TIEMPO]    [decimal](6, 0),
	[COMPRAS_ACC_ID_SUC]       [decimal](18, 0),
	[COMPRAS_ACC_FECHA]        [date],
	[COMPRAS_ACC_PRECIO]       [decimal](18, 2),
	[COMPRAS_ACC_CANT]         [decimal](18, 0),
    CONSTRAINT [PK_COMPRAS_ACC] PRIMARY KEY ([COMPRAS_ACC_ID])
);
GO

/****** Tabla VENTAS_ACC ******/
CREATE TABLE [ANONIMOUS].[VENTAS_ACC] (
	[VENTAS_ACC_ID]			 [decimal](18, 0) IDENTITY,
	[VENTAS_ACC_NUM]		 [decimal](18, 0), 
	[VENTAS_ACC_ID_ACC]		 [decimal](18, 0),
	[VENTAS_ACC_INDEX]		 [decimal](18, 0),
	[VENTAS_ACC_ID_TIEMPO]	 [decimal](6, 0),
	[VENTAS_ACC_ID_SUC]		 [decimal](18, 0),
	[VENTAS_ACC_EDAD_CLI]    [decimal](18, 0),
	[VENTAS_ACC_FECHA]       [date],
	[VENTAS_ACC_PRECIO]      [decimal](18, 2),
	[VENTAS_ACC_CANT]        [decimal](18, 0),
    CONSTRAINT [PK_VENTAS_ACC] PRIMARY KEY ([VENTAS_ACC_ID])
);
GO

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------ FOREIGN KEYS -----------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

----- FK BI_SUCURSAL - SUCURSAL_CIUDAD -> CIUDAD_ID -----
ALTER TABLE [ANONIMOUS].[BI_SUCURSAL]  WITH CHECK ADD  CONSTRAINT [FK_BI_Sucursal_Ciudad] FOREIGN KEY([SUCURSAL_CIUDAD]) REFERENCES [ANONIMOUS].[BI_CIUDAD] ([CIUDAD_ID])
GO

----- FK BI_COMPRA_PC - COMPRA_PC_ID_PC -> PC_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_PC] FOREIGN KEY([COMPRA_PC_ID_PC]) REFERENCES [ANONIMOUS].[BI_PC] ([PC_ID])
GO
----- FK BI_COMPRA_PC - COMPRA_PC_ID_TIEMPO -> TIEMPO_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_PC_Tiempo] FOREIGN KEY([COMPRA_PC_ID_TIEMPO]) REFERENCES [ANONIMOUS].[BI_TIEMPO] ([TIEMPO_ID])
GO
----- FK BI_COMPRA_PC - COMPRA_PC_ID_SUC -> SUCURSAL_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_PC_Suc] FOREIGN KEY([COMPRA_PC_ID_SUC]) REFERENCES [ANONIMOUS].[BI_SUCURSAL] ([SUCURSAL_ID])
GO
----- FK BI_COMPRA_PC - COMPRA_PC_ID_DISCO_RG -> DISCO_RG_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_PC_Disco] FOREIGN KEY([COMPRA_PC_ID_DISCO_RG]) REFERENCES [ANONIMOUS].[BI_DISCO_RG] ([DISCO_RG_ID])
GO
----- FK BI_COMPRA_PC - COMPRA_PC_ID_MEM_RAM -> MEM_RAM_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_PC_MemRam] FOREIGN KEY([COMPRA_PC_ID_MEM_RAM]) REFERENCES [ANONIMOUS].[BI_MEM_RAM] ([MEM_RAM_ID])
GO
----- FK BI_COMPRA_PC - COMPRA_PC_ID_MICRO_PRO -> MICRO_PRO_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_PC_Micro_pro] FOREIGN KEY([COMPRA_PC_ID_MICRO_PRO]) REFERENCES [ANONIMOUS].[BI_MICRO_PRO] ([MICRO_PRO_ID])
GO
----- FK BI_COMPRA_PC - COMPRA_PC_ID_PLACA_V -> PLA_VIDEO_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_PC_Placa_Vid] FOREIGN KEY([COMPRA_PC_ID_PLACA_V]) REFERENCES [ANONIMOUS].[BI_PLA_VIDEO] ([PLA_VIDEO_ID])
GO

----- FK BI_COMPRA_ACC - COMPRA_ACC_ID_ACC -> ACCESORIO_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_ACC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_ACC] FOREIGN KEY([COMPRA_ACC_ID_ACC]) REFERENCES [ANONIMOUS].[BI_ACCESORIO] ([ACCESORIO_ID])
GO
----- FK BI_COMPRA_ACC - COMPRA_ACC_ID_TIEMPO -> TIEMPO_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_ACC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_ACC_Tiempo] FOREIGN KEY([COMPRA_ACC_ID_TIEMPO]) REFERENCES [ANONIMOUS].[BI_TIEMPO] ([TIEMPO_ID])
GO
----- FK BI_COMPRA_ACC - COMPRA_ACC_ID_SUC -> SUCURSAL_ID -----
ALTER TABLE [ANONIMOUS].[BI_COMPRA_ACC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Compra_ACC_Suc] FOREIGN KEY([COMPRA_ACC_ID_SUC]) REFERENCES [ANONIMOUS].[BI_SUCURSAL] ([SUCURSAL_ID])
GO

----- FK BI_VENTA_PC - VENTA_PC_ID_PC -> PC_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_PC] FOREIGN KEY([VENTA_PC_ID_PC]) REFERENCES [ANONIMOUS].[BI_PC] ([PC_ID])
GO
----- FK BI_VENTA_PC - VENTA_PC_ID_TIEMPO -> TIEMPO_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_PC_Tiempo] FOREIGN KEY([VENTA_PC_ID_TIEMPO]) REFERENCES [ANONIMOUS].[BI_TIEMPO] ([TIEMPO_ID])
GO
----- FK BI_VENTA_PC - VENTA_PC_ID_SUC -> SUCURSAL_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_PC_Suc] FOREIGN KEY([VENTA_PC_ID_SUC]) REFERENCES [ANONIMOUS].[BI_SUCURSAL] ([SUCURSAL_ID])
GO
----- FK BI_VENTA_PC - VENTA_PC_ID_DISCO_RG -> DISCO_RG_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_PC_Disco] FOREIGN KEY([VENTA_PC_ID_DISCO_RG]) REFERENCES [ANONIMOUS].[BI_DISCO_RG] ([DISCO_RG_ID])
GO
----- FK BI_VENTA_PC - VENTA_PC_ID_MEM_RAM -> MEM_RAM_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_PC_MemRam] FOREIGN KEY([VENTA_PC_ID_MEM_RAM]) REFERENCES [ANONIMOUS].[BI_MEM_RAM] ([MEM_RAM_ID])
GO
----- FK BI_VENTA_PC - VENTA_PC_ID_MICRO_PRO -> MICRO_PRO_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_PC_Micro_pro] FOREIGN KEY([VENTA_PC_ID_MICRO_PRO]) REFERENCES [ANONIMOUS].[BI_MICRO_PRO] ([MICRO_PRO_ID])
GO
----- FK BI_VENTA_PC - VENTA_PC_ID_PLACA_V -> PLA_VIDEO_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_PC_Placa_Vid] FOREIGN KEY([VENTA_PC_ID_PLACA_V]) REFERENCES [ANONIMOUS].[BI_PLA_VIDEO] ([PLA_VIDEO_ID])
GO
----- FK BI_VENTA_PC - VENTA_PC_ID_EDAD_CLI -> RANGO_EDAD_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_PC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_PC_Cliente] FOREIGN KEY([VENTA_PC_ID_EDAD_CLI]) REFERENCES [ANONIMOUS].[BI_RANGO_EDAD] ([RANGO_EDAD_ID])
GO

----- FK BI_VENTA_ACC - VENTA_ACC_ID_ACC -> ACCESORIO_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_ACC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_ACC] FOREIGN KEY([VENTA_ACC_ID_ACC]) REFERENCES [ANONIMOUS].[BI_ACCESORIO] ([ACCESORIO_ID])
GO
----- FK BI_VENTA_ACC - VENTA_ACC_ID_TIEMPO -> TIEMPO_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_ACC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_ACC_Tiempo] FOREIGN KEY([VENTA_ACC_ID_TIEMPO]) REFERENCES [ANONIMOUS].[BI_TIEMPO] ([TIEMPO_ID])
GO
----- FK BI_VENTA_ACC - VENTA_ACC_ID_SUC -> SUCURSAL_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_ACC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_ACC_Suc] FOREIGN KEY([VENTA_ACC_ID_SUC]) REFERENCES [ANONIMOUS].[BI_SUCURSAL] ([SUCURSAL_ID])
GO
----- FK BI_VENTA_ACC - VENTA_ACC_ID_EDAD_CLI -> RANGO_EDAD_ID -----
ALTER TABLE [ANONIMOUS].[BI_VENTA_ACC]  WITH CHECK ADD  CONSTRAINT [FK_BI_Venta_ACC_Cliente] FOREIGN KEY([VENTA_ACC_ID_EDAD_CLI]) REFERENCES [ANONIMOUS].[BI_RANGO_EDAD] ([RANGO_EDAD_ID])
GO

----- FK BI_STOCK_ACC - STOCK_SUCURSAL -> SUCURSAL_ID -----
ALTER TABLE [ANONIMOUS].[BI_STOCK_ACC] WITH CHECK ADD  CONSTRAINT [FK_BI_STOCK_ACC_SUCURSAL] FOREIGN KEY([STOCK_SUCURSAL]) REFERENCES [ANONIMOUS].[BI_SUCURSAL] ([SUCURSAL_ID])
GO
----- FK BI_STOCK_ACC - STOCK_TIEMPO -> TIMEPO_ID -----
ALTER TABLE [ANONIMOUS].[BI_STOCK_ACC] WITH CHECK ADD  CONSTRAINT [FK_BI_STOCK_ACC_TIEMPO] FOREIGN KEY([STOCK_TIEMPO]) REFERENCES [ANONIMOUS].[BI_TIEMPO] ([TIEMPO_ID])
GO
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------ CARGA DE DATOS ---------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

/****** Load BI_TIEMPO ******/
INSERT INTO [ANONIMOUS].[BI_TIEMPO]
SELECT YEAR ([FACT_FECHA]) * 100 +  MONTH([FACT_FECHA]) AS [ID],
		YEAR ([FACT_FECHA]) AS [ANIO], 
		MONTH([FACT_FECHA]) AS [MES]
FROM [GD1C2021].[ANONIMOUS].[FACTURA]
UNION 
SELECT YEAR ([COMPRA_FECHA]) * 100  + MONTH([COMPRA_FECHA]) AS [ID],
       YEAR ([COMPRA_FECHA]) AS [ANIO], 
       MONTH([COMPRA_FECHA]) AS [MES]
FROM [GD1C2021].[ANONIMOUS].[COMPRA]
ORDER BY ID;
GO

/****** Load BI_CIUDAD ******/
INSERT INTO [ANONIMOUS].[BI_CIUDAD]
SELECT *
FROM [GD1C2021].[ANONIMOUS].[CIUDAD];
GO

/****** Load BI_SUCURSAL ******/
INSERT INTO [ANONIMOUS].[BI_SUCURSAL]
SELECT *
FROM [GD1C2021].[ANONIMOUS].[SUCURSAL];
GO

/****** Load BI_RANGO_EDAD ******/
INSERT INTO [ANONIMOUS].[BI_RANGO_EDAD](RANGO_EDAD_ID, RANGO_EDAD_DESC) 
VALUES (1, '18 - 30 años'), (2, '31 - 50 años'), (3, '> 50')
GO

/****** Load BI_PC ******/
INSERT INTO [ANONIMOUS].[BI_PC]
SELECT DISTINCT [PC_ID], 
                [PC_COD]
  FROM [GD1C2021].[ANONIMOUS].[PC]
GO

/****** Load BI_ACCESORIO ******/
INSERT INTO [ANONIMOUS].[BI_ACCESORIO]
SELECT [ACC_ID],
       [ACC_CODIGO],
	   [ACC_DESC]
FROM [ANONIMOUS].[ACCESORIO]
GO

/****** Load BI_DISCO_RG ******/
INSERT INTO [ANONIMOUS].[BI_DISCO_RG] ([DISCO_RG_ID],[DISCO_RG_COD],[DISCO_RG_TIPO],[DISCO_RG_CAPACIDAD],[DISCO_RG_VELOCIDAD],[DISCO_RG_FABRICANTE])
SELECT  [COM_ID],
		[COM_COD],
		[COM_TECNOLOGIA],
		[COM_CAPACIDAD],
		[COM_VELOCIDAD],
		[COM_FABRICANTE]
FROM [GD1C2021].[ANONIMOUS].[COMPONENTE]
WHERE [COM_TIPO] = 1 
ORDER BY [COM_ID];
GO

/****** Load BI_MEM_RAM ******/
INSERT INTO [ANONIMOUS].[BI_MEM_RAM] ([MEM_RAM_ID],[MEM_RAM_COD],[MEM_RAM_TIPO],[MEM_RAM_CAPACIDAD],[MEM_RAM_VELOCIDAD],[MEM_RAM_FABRICANTE])
SELECT	[COM_ID],
		[COM_COD],
		[COM_TECNOLOGIA],
		[COM_CAPACIDAD],
		[COM_VELOCIDAD],
		[COM_FABRICANTE]
FROM [GD1C2021].[ANONIMOUS].[COMPONENTE]
WHERE [COM_TIPO] = 2
ORDER BY [COM_ID];
GO

/****** Load BI_MICRO_PRO ******/
INSERT INTO [ANONIMOUS].[BI_MICRO_PRO] ([MICRO_PRO_ID],[MICRO_PRO_COD],[MIC_PRO_VELOCIDAD],[MIC_PRO_FABRICANTE],[MIC_PRO_CANT_HILOS],[MIC_PRO_CACHE])
SELECT	[COM_ID],
		[COM_COD],
		[COM_VELOCIDAD],
		[COM_FABRICANTE],
		[COM_MICRO_CANT_HILOS],
		[COM_MICRO_CACHE]
FROM [GD1C2021].[ANONIMOUS].[COMPONENTE]
WHERE [COM_TIPO] = 3
ORDER BY [COM_ID];
GO

/****** Load BI_PLA_VIDEO ******/
INSERT INTO [ANONIMOUS].[BI_PLA_VIDEO] ([PLA_VIDEO_ID],[PLA_VIDEO_MODELO],[PLA_VIDEO_CAPACIDAD],[PLA_VIDEO_VELOCIDAD],[PLA_VIDEO_FABRICANTE],[PLA_VIDEO_VIDEO_CHIPSET])
SELECT	[COM_ID],
		[COM_VIDEO_MODELO],
		[COM_CAPACIDAD],
		[COM_VELOCIDAD],
		[COM_FABRICANTE],
		[COM_VIDEO_CHIPSET]
FROM [GD1C2021].[ANONIMOUS].[COMPONENTE]
WHERE [COM_TIPO] = 4
ORDER BY [COM_ID];
GO

/****** Load COMPRAS_PC ******/
INSERT INTO [ANONIMOUS].[COMPRAS_PC]
SELECT [COMPRA].[COMPRA_NUM] AS [COMPRAS_PC_NRO],
       [PRODUCTO].[PROD_ID] AS [COMPRAS_PC],
	   ROW_NUMBER() OVER
	   (PARTITION BY [PROD_ID]
	                ,[COMPRA].[COMPRA_SUC] 
		    ORDER BY [PROD_ID],[COMPRA].[COMPRA_SUC],[COMPRA].[COMPRA_FECHA]) AS [COMPRAS_PC_INDEX],
	   YEAR ([COMPRA].[COMPRA_FECHA]) * 100 +  MONTH([COMPRA].[COMPRA_FECHA]) AS [COMPRAS_PC_TIEMPO],
	   [COMPRA].[COMPRA_SUC] AS [COMPRAS_PC_SUC],
	   (SELECT [COM_ID] FROM ANONIMOUS.PC, ANONIMOUS.COMPONENTE
	    WHERE COM_ID = PC_COMPONENTE and COM_TIPO = 1 and PC_ID = PROD_ID) AS [COMPRAS_PC_DISCO],
	   (SELECT [COM_ID] FROM ANONIMOUS.PC, ANONIMOUS.COMPONENTE
	    WHERE COM_ID = PC_COMPONENTE and COM_TIPO = 2 and PC_ID = PROD_ID) AS [COMPRAS_PC_MEM_RAM],
       (SELECT [COM_ID] FROM ANONIMOUS.PC, ANONIMOUS.COMPONENTE
	    WHERE COM_ID = PC_COMPONENTE and COM_TIPO = 3 and PC_ID = PROD_ID) AS [COMPRAS_PC_MICRO],
       (SELECT [COM_ID] FROM ANONIMOUS.PC, ANONIMOUS.COMPONENTE
	    WHERE COM_ID = PC_COMPONENTE and COM_TIPO = 4 and PC_ID = PROD_ID) AS [COMPRAS_PC_VIDEO],
	   CONVERT(DATE, [COMPRA].[COMPRA_FECHA], 23) AS [COMPRAS_PC_FECHA],
	   [ITEM_COMPRA].[ITEM_COM_PRECIO] AS [COMPRAS_PC_PRECIO],
	   [ITEM_COMPRA].[ITEM_COM_CANT] AS [COMPRAS_PC_CANT]	   
FROM [ANONIMOUS].[COMPRA] 
    ,[ANONIMOUS].[ITEM_COMPRA] 
	,[ANONIMOUS].[PRODUCTO]
WHERE [COMPRA_NUM] = [ITEM_COM_NUM]
  AND [ITEM_COM_PROD] = [PROD_ID]
  AND [PROD_TIPO] = 1
ORDER BY [COMPRAS_PC]
        ,[COMPRA].[COMPRA_SUC]
		,[COMPRA].[COMPRA_FECHA]
GO

/****** Load BI_COMPRA_PC ******/
INSERT INTO [ANONIMOUS].[BI_COMPRA_PC]
SELECT   [COMPRAS_PC_ID_PC]
        ,[COMPRAS_PC_ID_SUC]
		,[COMPRAS_PC_ID_TIEMPO]
		,[COMPRAS_PC_ID_DISCO_RG]
		,[COMPRAS_PC_ID_MEM_RAM]
		,[COMPRAS_PC_ID_MICRO_PRO]
		,[COMPRAS_PC_ID_PLACA_V]
	    ,AVG([COMPRAS_PC_PRECIO]) -- PRECIO COMPRA PROMEDIO
	    ,SUM([COMPRAS_PC_CANT])   -- CANTIDAD COMPRA
FROM [ANONIMOUS].[COMPRAS_PC]
GROUP BY [COMPRAS_PC_ID_PC]
        ,[COMPRAS_PC_ID_SUC]
		,[COMPRAS_PC_ID_TIEMPO]
		,[COMPRAS_PC_ID_DISCO_RG]
		,[COMPRAS_PC_ID_MEM_RAM]
		,[COMPRAS_PC_ID_MICRO_PRO]
		,[COMPRAS_PC_ID_PLACA_V]
ORDER BY [COMPRAS_PC_ID_PC]
        ,[COMPRAS_PC_ID_SUC]
		,[COMPRAS_PC_ID_TIEMPO]
		,[COMPRAS_PC_ID_DISCO_RG]
		,[COMPRAS_PC_ID_MEM_RAM]
		,[COMPRAS_PC_ID_MICRO_PRO]
		,[COMPRAS_PC_ID_PLACA_V]
GO

/****** Load COMPRAS_ACC ******/
INSERT INTO [ANONIMOUS].[COMPRAS_ACC]
SELECT [COMPRA].[COMPRA_NUM] AS [COMPRAS_ACC_NUM],
       [PRODUCTO].[PROD_ID] AS [COMPRAS_ACC],
	   ROW_NUMBER() OVER
	   (PARTITION BY [PROD_ID]
					,[COMPRA].[COMPRA_SUC]
	        ORDER BY [PROD_ID],[COMPRA].[COMPRA_SUC],[COMPRA].[COMPRA_FECHA]) AS [COMPRAS_ACC_INDEX],
	   YEAR ([COMPRA].[COMPRA_FECHA]) * 100 +  MONTH([COMPRA].[COMPRA_FECHA]) AS [COMPRAS_ACC_TIEMPO],
	   [COMPRA].[COMPRA_SUC] AS [COMPRAS_ACC_SUC],
	   CONVERT(DATE, [COMPRA].[COMPRA_FECHA], 23) AS [COMPRAS_ACC_FECHA],
	   [ITEM_COMPRA].[ITEM_COM_PRECIO] AS [COMPRAS_ACC_PRECIO],
	   [ITEM_COMPRA].[ITEM_COM_CANT] AS [COMPRAS_ACC_CANT]	   
FROM [ANONIMOUS].[COMPRA] 
    ,[ANONIMOUS].[ITEM_COMPRA] 
	,[ANONIMOUS].[PRODUCTO]
WHERE [COMPRA_NUM] = [ITEM_COM_NUM]
  AND [ITEM_COM_PROD] = [PROD_ID]
  AND [PROD_TIPO] = 2
ORDER BY [COMPRAS_ACC]
        ,[COMPRA].[COMPRA_SUC]
		,[COMPRA].[COMPRA_FECHA]
GO

/****** Load BI_COMPRA_ACC ******/
INSERT INTO [ANONIMOUS].[BI_COMPRA_ACC]
SELECT [COMPRAS_ACC_ID_ACC]
      ,[COMPRAS_ACC_ID_SUC]
	  ,[COMPRAS_ACC_ID_TIEMPO]
	  ,AVG([COMPRAS_ACC_PRECIO]) -- PRECIO COMPRA PROMEDIO
	  ,SUM([COMPRAS_ACC_CANT])   -- CANTIDAD COMPRA
FROM [ANONIMOUS].[COMPRAS_ACC]
GROUP BY [COMPRAS_ACC_ID_ACC]
        ,[COMPRAS_ACC_ID_SUC]
	    ,[COMPRAS_ACC_ID_TIEMPO]
ORDER BY [COMPRAS_ACC_ID_ACC]
        ,[COMPRAS_ACC_ID_SUC]
	    ,[COMPRAS_ACC_ID_TIEMPO]
GO

/****** Load VENTAS_PC ******/
INSERT INTO [ANONIMOUS].[VENTAS_PC]
SELECT [FACTURA].[FACT_NUM] AS [VENTAS_PC_NRO],
       [PRODUCTO].[PROD_ID] AS [VENTAS_PC],
	   ROW_NUMBER() OVER
	   (PARTITION BY [PROD_ID] 
	                ,[FACTURA].[FACT_SUC]
	        ORDER BY [PROD_ID],[FACTURA].[FACT_SUC],[FACTURA].[FACT_FECHA]) AS [VENTAS_PC_INDEX],
	   YEAR ([FACTURA].[FACT_FECHA]) * 100 +  MONTH([FACTURA].[FACT_FECHA]) AS [VENTAS_PC_TIEMPO],
	   [FACTURA].[FACT_SUC] AS [VENTAS_PC_SUC],
	   CASE 
	     WHEN DATEDIFF(YEAR,[CLI_FEC_NAC],[FACT_FECHA]) >= 18
		      AND
			  DATEDIFF(YEAR,[CLI_FEC_NAC],[FACT_FECHA]) <= 30
			  THEN 1
		 WHEN DATEDIFF(YEAR,[CLI_FEC_NAC],[FACT_FECHA]) >= 31
		      AND
			  DATEDIFF(YEAR,[CLI_FEC_NAC],[FACT_FECHA]) <= 50
			  THEN 2
		 ELSE 3
	   END AS [VENTAS_PC_EDAD_CLI],
	   (SELECT [COM_ID] FROM ANONIMOUS.PC, ANONIMOUS.COMPONENTE
	    WHERE COM_ID = PC_COMPONENTE and COM_TIPO = 1 and PC_ID = PROD_ID) AS [VENTAS_PC_DISCO],
	   (SELECT [COM_ID] FROM ANONIMOUS.PC, ANONIMOUS.COMPONENTE
	    WHERE COM_ID = PC_COMPONENTE and COM_TIPO = 2 and PC_ID = PROD_ID) AS [VENTAS_PC_MEM_RAM],
       (SELECT [COM_ID] FROM ANONIMOUS.PC, ANONIMOUS.COMPONENTE
	    WHERE COM_ID = PC_COMPONENTE and COM_TIPO = 3 and PC_ID = PROD_ID) AS [VENTAS_PC_MICRO],
       (SELECT [COM_ID] FROM ANONIMOUS.PC, ANONIMOUS.COMPONENTE
	    WHERE COM_ID = PC_COMPONENTE and COM_TIPO = 4 and PC_ID = PROD_ID) AS [VENTAS_PC_VIDEO],
	   CONVERT(DATE, [FACTURA].[FACT_FECHA], 23) AS [VENTAS_PC_FECHA],
	   [ITEM_FACTURA].[ITEM_FACT_PRECIO] AS [VENTAS_PC_PRECIO],
	   [ITEM_FACTURA].[ITEM_FACT_CANT] AS [VENTAS_PC_CANT]	   
FROM [ANONIMOUS].[FACTURA], 
     [ANONIMOUS].[ITEM_FACTURA], 
	 [ANONIMOUS].[PRODUCTO]
	,[ANONIMOUS].[CLIENTE]
WHERE [FACT_NUM] = [ITEM_FACT_NUM]
  AND [ITEM_FACT_PROD] = [PROD_ID]
  AND [FACT_CLIENTE] = [CLI_ID]
  AND [PROD_TIPO] = 1
ORDER BY [VENTAS_PC]
		,[FACTURA].[FACT_SUC]
		,[FACTURA].[FACT_FECHA]
GO

/****** Load BI_VENTA_PC ******/
INSERT INTO [ANONIMOUS].[BI_VENTA_PC]
SELECT   [VENTAS_PC_ID_PC]
        ,[VENTAS_PC_ID_SUC]
		,[VENTAS_PC_ID_TIEMPO]
		,[VENTAS_PC_EDAD_CLI]
		,[VENTAS_PC_ID_DISCO_RG]
		,[VENTAS_PC_ID_MEM_RAM]
		,[VENTAS_PC_ID_MICRO_PRO]
		,[VENTAS_PC_ID_PLACA_V]
	    ,AVG([VENTAS_PC_PRECIO]) -- PRECIO VENTA PROMEDIO
	    ,SUM([VENTAS_PC_CANT])   -- CANTIDAD VENTA
	    ,AVG(DATEDIFF(DAY,[COMPRAS_PC_FECHA],[VENTAS_PC_FECHA])) -- PROMEDIO TIEMPO STOCK
	    ,SUM((([VENTAS_PC_PRECIO] * [VENTAS_PC_CANT]) / 1.20) * 0.2) -- GANANCIA 
FROM [ANONIMOUS].[COMPRAS_PC]
    ,[ANONIMOUS].[VENTAS_PC]
WHERE [COMPRAS_PC_ID_PC]  = [VENTAS_PC_ID_PC]
  AND [COMPRAS_PC_ID_SUC] = [VENTAS_PC_ID_SUC]
  AND [COMPRAS_PC_INDEX]  = [VENTAS_PC_INDEX]  
GROUP BY [VENTAS_PC_ID_PC]
        ,[VENTAS_PC_ID_SUC]
		,[VENTAS_PC_ID_TIEMPO]
		,[VENTAS_PC_EDAD_CLI]
		,[VENTAS_PC_ID_DISCO_RG]
		,[VENTAS_PC_ID_MEM_RAM]
		,[VENTAS_PC_ID_MICRO_PRO]
		,[VENTAS_PC_ID_PLACA_V]
ORDER BY [VENTAS_PC_ID_PC]
        ,[VENTAS_PC_ID_SUC]
		,[VENTAS_PC_ID_TIEMPO]
		,[VENTAS_PC_EDAD_CLI]
		,[VENTAS_PC_ID_DISCO_RG]
		,[VENTAS_PC_ID_MEM_RAM]
		,[VENTAS_PC_ID_MICRO_PRO]
		,[VENTAS_PC_ID_PLACA_V]
GO

/****** Load VENTAS_ACC ******/
INSERT INTO [ANONIMOUS].[VENTAS_ACC]
SELECT [FACTURA].[FACT_NUM] AS [VENTAS_ACC_NUM],
       [PRODUCTO].[PROD_ID] AS [VENTAS_ACC],
	   ROW_NUMBER() OVER(PARTITION BY [PROD_ID] 
					        ,[FACTURA].[FACT_SUC]
	                         ORDER BY [PROD_ID],[FACTURA].[FACT_SUC],[FACTURA].[FACT_FECHA]) AS [VENTAS_ACC_INDEX],
	   YEAR ([FACTURA].[FACT_FECHA]) * 100 +  MONTH([FACTURA].[FACT_FECHA]) AS [VENTAS_ACC_TIEMPO],
	   [FACTURA].[FACT_SUC] AS [VENTAS_ACC_SUC],
	   CASE 
	     WHEN DATEDIFF(YEAR,[CLI_FEC_NAC],[FACT_FECHA]) >= 18
		      AND
			  DATEDIFF(YEAR,[CLI_FEC_NAC],[FACT_FECHA]) <= 30
			  THEN 1
		 WHEN DATEDIFF(YEAR,[CLI_FEC_NAC],[FACT_FECHA]) >= 31
		      AND
			  DATEDIFF(YEAR,[CLI_FEC_NAC],[FACT_FECHA]) <= 50
			  THEN 2
		 ELSE 3
	   END AS [VENTAS_ACC_EDAD_CLI],
	   CONVERT(DATE, [FACTURA].[FACT_FECHA], 23)  AS [VENTAS_ACC_FECHA],
	   [ITEM_FACTURA].[ITEM_FACT_PRECIO] AS [VENTAS_ACC_PRECIO],
	   [ITEM_FACTURA].[ITEM_FACT_CANT] AS [VENTAS_ACC_CANT]	   
FROM [ANONIMOUS].[FACTURA], 
     [ANONIMOUS].[ITEM_FACTURA], 
	 [ANONIMOUS].[PRODUCTO]
	,[ANONIMOUS].[CLIENTE]
WHERE [FACT_NUM] = [ITEM_FACT_NUM]
  AND [ITEM_FACT_PROD] = [PROD_ID]
  AND [FACT_CLIENTE] = [CLI_ID]
  AND [PROD_TIPO] = 2
ORDER BY [VENTAS_ACC]
		,[FACTURA].[FACT_SUC]
		,[FACTURA].[FACT_FECHA]
GO

/****** Load BI_VENTA_ACC ******/
INSERT INTO [ANONIMOUS].[BI_VENTA_ACC]
SELECT [VENTAS_ACC_ID_ACC]
      ,[VENTAS_ACC_ID_SUC]
	  ,[VENTAS_ACC_ID_TIEMPO]
	  ,[VENTAS_ACC_EDAD_CLI]
	  ,AVG([VENTAS_ACC_PRECIO]) -- PRECIO VENTA PROMEDIO
	  ,SUM([VENTAS_ACC_CANT])   -- CANTIDAD VENTA
	  ,AVG(DATEDIFF(DAY,[COMPRAS_ACC_FECHA],[VENTAS_ACC_FECHA])) -- PROMEDIO TIEMPO STOCK
	  ,SUM((([VENTAS_ACC_PRECIO] * [VENTAS_ACC_CANT]) / 1.20) * 0.2) -- GANANCIA
FROM [ANONIMOUS].[COMPRAS_ACC]
    ,[ANONIMOUS].[VENTAS_ACC]
WHERE [COMPRAS_ACC_ID_ACC] = [VENTAS_ACC_ID_ACC]
  AND [COMPRAS_ACC_ID_SUC] = [VENTAS_ACC_ID_SUC]
  AND [COMPRAS_ACC_INDEX]  = [VENTAS_ACC_INDEX]   
GROUP BY [VENTAS_ACC_ID_ACC]
        ,[VENTAS_ACC_ID_SUC]
	    ,[VENTAS_ACC_ID_TIEMPO]
	    ,[VENTAS_ACC_EDAD_CLI]
ORDER BY [VENTAS_ACC_ID_ACC]
        ,[VENTAS_ACC_ID_SUC]
	    ,[VENTAS_ACC_ID_TIEMPO]
	    ,[VENTAS_ACC_EDAD_CLI]
GO

/****** Load BI_STOCK_ACC ******/
INSERT INTO [ANONIMOUS].[BI_STOCK_ACC] 
SELECT [STOCK_AUX].[SUCURSAL_ID]
      ,[STOCK_AUX].[TIEMPO_ID]
	  ,SUM([STOCK_AUX].[STOCK_MES]) OVER(PARTITION BY [STOCK_AUX].[SUCURSAL_ID] 
	                                         ORDER BY [STOCK_AUX].[SUCURSAL_ID] ASC
											         ,[STOCK_AUX].[TIEMPO_ID]   ASC) 
FROM
(
SELECT [SUCURSAL_ID]
      ,[TIEMPO_ID]
	  ,
	  (ISNULL((SELECT SUM(COMPRA_ACC_CANT)
	    FROM [ANONIMOUS].[BI_COMPRA_ACC]
		WHERE [COMPRA_ACC_ID_SUC]    = [SUCURSAL_ID]
		  AND [COMPRA_ACC_ID_TIEMPO] = [TIEMPO_ID]
		GROUP BY [COMPRA_ACC_ID_SUC]
		        ,[COMPRA_ACC_ID_TIEMPO]),0) -- CANTIDAD COMPRADA
		-
		ISNULL((SELECT SUM([VENTA_ACC_CANT])
	    FROM [ANONIMOUS].[BI_VENTA_ACC]
		WHERE [VENTA_ACC_ID_SUC]    = [SUCURSAL_ID]
		  AND [VENTA_ACC_ID_TIEMPO] = [TIEMPO_ID]
		GROUP BY [VENTA_ACC_ID_SUC]
		        ,[VENTA_ACC_ID_TIEMPO]),0)) -- CANTIDAD VENDIDA
		AS [STOCK_MES]
FROM [ANONIMOUS].[BI_SUCURSAL],
     [ANONIMOUS].[BI_TIEMPO]
) AS [STOCK_AUX]
GO

/****** Vista V_PROMEDIO_STOCK_PC ******/
-- Promedio de tiempo en stock de cada modelo de PC
CREATE VIEW [ANONIMOUS].[V_PROMEDIO_STOCK_PC]
AS
SELECT [PC_COD]
	   ,AVG ([VENTA_PC_DIAS_STOCK_PROM]) AS [PROMEDIO_TIEMPO_STOCK]
FROM [ANONIMOUS].[BI_VENTA_PC]
    ,[ANONIMOUS].[BI_PC]
GROUP BY [PC_COD]
GO

/****** Vista V_PRECIO_PC_COMPRA ******/
-- Precio promedio de PC's compradas
CREATE VIEW [ANONIMOUS].[V_PRECIO_PC_COMPRA]
AS
SELECT [PC_COD]
	   ,AVG ([COMPRA_PC_PRECIO_PROM]) AS [PROMEDIO_PRECIO_PC] 
FROM [ANONIMOUS].[BI_COMPRA_PC]
    ,[ANONIMOUS].[BI_PC]
WHERE [COMPRA_PC_ID_PC] = [PC_ID]
GROUP BY [PC_COD]
GO

/****** Vista V_PRECIO_PC_VENTA ******/
-- Precio promedio de PC's vendidas
CREATE VIEW [ANONIMOUS].[V_PRECIO_PC_VENTA]
AS
SELECT [PC_COD]
	   ,AVG ([VENTA_PC_PRECIO_PROM]) AS [PROMEDIO_PRECIO_PC] 
FROM [ANONIMOUS].[BI_VENTA_PC]
    ,[ANONIMOUS].[BI_PC]
GROUP BY [PC_COD]
GO

/****** Vista V_CANT_PC_COMPRA ******/
-- Cantidad de PC's compradas x sucursal x mes
CREATE VIEW [ANONIMOUS].[V_CANT_PC_COMPRA]
AS
SELECT [PC_COD]
	  ,[COMPRA_PC_ID_SUC]
	  ,[COMPRA_PC_ID_TIEMPO]
	  ,SUM([COMPRA_PC_CANT]) AS [CANT_TOTAL_PC]
FROM [ANONIMOUS].[BI_COMPRA_PC]
    ,[ANONIMOUS].[BI_PC]
GROUP BY [PC_COD],
         [COMPRA_PC_ID_SUC],
		 [COMPRA_PC_ID_TIEMPO]
GO

/****** Vista V_CANT_PC_VENTA ******/
-- Cantidad de PC's vendidas x sucursal x mes
CREATE VIEW [ANONIMOUS].[V_CANT_PC_VENTA]
AS
SELECT [PC_COD]
	  ,[VENTA_PC_ID_SUC]
	  ,[VENTA_PC_ID_TIEMPO]
	  ,SUM([VENTA_PC_CANT]) AS [CANT_TOTAL_PC]
FROM [ANONIMOUS].[BI_VENTA_PC]
    ,[ANONIMOUS].[BI_PC]
GROUP BY [PC_COD],
         [VENTA_PC_ID_SUC],
		 [VENTA_PC_ID_TIEMPO]
GO

/****** Vista V_GANANCIAS_PC ******/
-- Ganancia de PC's x sucursal x mes
CREATE VIEW [ANONIMOUS].[V_GANANCIAS_PC]
AS
SELECT [PC_COD]
      ,[VENTA_PC_ID_SUC] AS [SUCURSAL]
	  ,[VENTA_PC_ID_TIEMPO] AS [PERIODO]
	  ,SUM([VENTA_PC_GANANCIA]) AS [GANANCIA]
FROM [ANONIMOUS].[BI_VENTA_PC]
    ,[ANONIMOUS].[BI_PC]
GROUP BY [PC_COD]
        ,[VENTA_PC_ID_SUC]
	    ,[VENTA_PC_ID_TIEMPO]

GO

/****** Vista V_PRECIO_ACC_COMPRA ******/
-- Precio promedio de accesorios comprados
CREATE VIEW [ANONIMOUS].[V_PRECIO_ACC_COMPRA]
AS
SELECT [ACCESORIO_COD] 
	   ,AVG ([COMPRA_ACC_PRECIO_PROM]) AS [PRECIO_PROMEDIO]
FROM [ANONIMOUS].[BI_COMPRA_ACC]
    ,[ANONIMOUS].[BI_ACCESORIO]
WHERE [COMPRA_ACC_ID_ACC] = [ACCESORIO_ID]
GROUP BY [ACCESORIO_COD]
GO

/****** Vista V_PRECIO_ACC_VENTA ******/
-- Precio promedio de accesorios vendidos
CREATE VIEW [ANONIMOUS].[V_PRECIO_ACC_VENTA]
AS
SELECT [ACCESORIO_COD]
	  ,AVG ([VENTA_ACC_PRECIO_PROM]) AS [PRECIO_PROMEDIO]
FROM [ANONIMOUS].[BI_VENTA_ACC]
    ,[ANONIMOUS].[BI_ACCESORIO]
WHERE [VENTA_ACC_ID_ACC] = [ACCESORIO_ID]
GROUP BY [ACCESORIO_COD]
GO

/****** Vista V_GANANCIAS_ACC ******/
-- Ganancia de accesorios x sucursal x mes
CREATE VIEW [ANONIMOUS].[V_GANANCIAS_ACC]
AS
SELECT [ACCESORIO_COD]
      ,[VENTA_ACC_ID_SUC]
	  ,[VENTA_ACC_ID_TIEMPO]
	  ,SUM([VENTA_ACC_GANANCIA]) AS [GANANCIA]
FROM [ANONIMOUS].[BI_VENTA_ACC]
    ,[ANONIMOUS].[BI_ACCESORIO]
WHERE [VENTA_ACC_ID_ACC] = [ACCESORIO_ID]
GROUP BY [ACCESORIO_COD]
        ,[VENTA_ACC_ID_SUC]
	    ,[VENTA_ACC_ID_TIEMPO]
GO

/****** Vista V_PROMEDIO_STOCK_ACC ******/
-- Promedio de tiempo en stock de cada modelo de accesorio
CREATE VIEW [ANONIMOUS].[V_PROMEDIO_STOCK_ACC]
AS
SELECT [ACCESORIO_COD]
      ,AVG([VENTA_ACC_DIAS_STOCK_PROM]) AS [DIAS_STOCK_PROMEDIO]
FROM [ANONIMOUS].[BI_VENTA_ACC]
    ,[ANONIMOUS].[BI_ACCESORIO]
WHERE [VENTA_ACC_ID_ACC] = [ACCESORIO_ID] 
GROUP BY [ACCESORIO_COD]
GO

/****** Vista V_MAX_STOCK_ACC ******/
-- Maxima cantidad de STOCK por cada sucursal (ANUAL)
CREATE VIEW [ANONIMOUS].[V_MAX_STOCK_ACC]
AS
SELECT [STOCK_SUCURSAL]    AS [SUCURSAL]
     , [TIEMPO_ANIO]       AS [ANIO]
	 , MAX([STOCK_CANTIDAD]) AS [STOCK]
FROM [ANONIMOUS].[BI_STOCK_ACC]
    ,[ANONIMOUS].[BI_TIEMPO]
WHERE [STOCK_TIEMPO] = [TIEMPO_ID]
GROUP BY [STOCK_SUCURSAL]
        ,[TIEMPO_ANIO] 
GO